### ISSUE TITLE
Unused inputs

### ISSUE THREAD

**Issue by karikarshivani** [mitre/crunchy-data-postgresql-stig-baseline#4]
There are inputs listed in `inspec.yml` that are not used in any controls. They need to be reviewed to be used in controls or removed from `inspec.yml`:

- [ ] pg_owner_password
- [ ] pg_user_password
- [ ] login_host
- [ ] pg_syslog_owner
- [ ] pg_syslog_facility
- [ ] pg_conf_mode
- [ ] pg_ssl
- [ ] pg_log_dest
- [ ] pgaudit_log_items
- [ ] pgaudit_log_line_items

**Comment by ssayed118** [comment]
pg_conf_mode could be used for the following controls to parameterize the value 0600:
V-233514
V-233618
V-233523
V-2335331
V-233549

**Comment by karikarshivani** [comment]
Consider using inputs directly in the controls instead of assigning them to a variable.

**Comment by ejaronne** [comment]
> pg_conf_mode could be used for the following controls to parameterize the value 0600: V-233514 V-233618 V-233523 V-2335331 V-233549

I think it is rare someone in the field would want to change this permission. Never done this for any other file/dir/exe permissions in operating system or host-based settings.

**Comment by ejaronne** [comment]
For inputs declared long ago in the inspec.yml by the Crunchy folks, I think they were anticipating the possibility of using them but turned out not using them. Rather than remove them from inspec.yml, maybe we can comment them out with the comment: "for possible future use"
